string() is declared as private; usage of c_str() is better.
* This prevents error-messages like this: "hardware/qcom-caf/msm8994/display/libhwcomposer/hwc.cpp:989:24: error: 'string' is a private member of 'android::String8'".

Change-Id: Ib461bfa00f7313c82b9c3c6a24f5c28850aaad4d